### ISSUE TITLE
MAJOR: **Understanding of how to use the functionality**

### ISSUE THREAD

**Issue by Janette-cwk** [BeckMillet/INFO442Team5#50]
**Describe the issue**
The URL brings me to the sign in page, then after I sign in, I saw a input field for daily budget, then a overall balance, and input fields for enter transaction. I don't really understand how the web app works and what it does because there is no description text on the page, and there is no about page to tell me what does this app do or why do I need it.  I don't know why do I need to enter my budget and what does it do after I enter transactions.

**To Reproduce**
1. Go to landing page
2. Sign in
3. A page with multiple input fields show up

**Expected behavior**
I expected there is some text or a page to tell me what does this web app do, why do I need it or what are these input fields for.

**Comment by thoalala** [comment]
Thanks @Janette-cwk for the feedback!

I agree that it wasn't so clear on how to use the product. Our MVP was to get the functionality working. What you're describing in this ticket could be considered an enhancement. In future works, we may look into providing a landing page or some more documentation on our product.

I would say this may be a minor issue since it's not breaking any functionality. This should be categorized as an enhancement rather than a bug.

Lmk if this makes any sense and if we can reprioritize this as a minor bug or a future enhancement.

**Comment by thoalala** [comment]
Closing. Not a real failure. This can be considered a future enhancement to our application but not in scope for the project.
