### ISSUE TITLE
MINOR: Remove transaction button 

### ISSUE THREAD

**Issue by magalj** [BeckMillet/INFO442Team5#52]
Remove button
Minor
Description:
The remove button of a transaction only shows up when you click on the transaction. Having a signifier or just letting the remove button always present could be an option!
Reproduction:
1.	Sign In
2.	Add a budget
3.	Add an item transaction and amount
4.	Click on the transaction and the remove button will appear

**Comment by thoalala** [comment]
The remove button interaction was by design and part of our application's UX flow. This ticket could be considered a usability enhancement if more users note it as a problem. 

It does not affect the functionality of removing transactions, let's categorize this as a non-issue or enhancement on Monday. 

**Designers**: What do you think? The remove button shouldn't always exist because the app will look cluttered but an x on the side could work.

**Comment by angelashen0607** [comment]
I was thinking an x on the top right side of the card may work too! But it really depends on if it's workable for the coders. I don't think this is a major concern if it's undoable or takes up too much time tho!

**Comment by angelashen0607** [comment]
Since most of our users are aware of the click-and-remove feature, we decided to keep the design to keep our app cleaner and more minimal.
