### ISSUE TITLE
MAJOR: **CAN'T FIND WAY TO CREATE ACCOUNT. JUST SIGN IN**

### ISSUE THREAD

**Issue by gcaelin30** [BeckMillet/INFO442Team5#53]
As soon as I clicked the link from the Canvas homepage, I was taken to the Sprout homepage which shows "SIGN IN" and two box cards asking to Sign in via email and the other via google
Now, as a normal user with no clue as to what this is except for the readme file, I have no idea what to do now.... I for sure have never created a Sprout account before so I can't sign in
It also doesn't give me directions on how to create an account or if I sign in with my UW account or something?
Just confused and can't access the site.

**Comment by thoalala** [comment]
Reference Flex requirement 1: 
{Revised & Completed: A new user will see a sign-in screen and be prompted to register an email and password. They will be led into the main screen upon completion. Revised requirement so new users are no longer prompted with a sign-up button because Firebase does not provide functions to change the text of their authentication buttons.}

- Firebase does not allow us to create a sign-up button
- Once a new user enters an unknown email address, they are led to a create account form.

![image](https://user-images.githubusercontent.com/24668595/83848105-35850e00-a6c2-11ea-812e-81c8b005300d.png)

**Team:** Not sure if we should prioritize this as a major bug because the sign-in/sign-up functionality is not broken. There is a workaround of users simply entering an email using either of the sign-in options. However, we should consider the app user experience and add more information on the sign-in page. I suggest reprioritizing as a minor bug and fix or label it as an non-issue on Monday.

**Comment by thoalala** [comment]
Not a real failure. Closing because the functionality is not broken. Signing-in is creating an account in the user experience of our app.
