### ISSUE TITLE
MINOR: Overall Balance can exceed set daily budget

### ISSUE THREAD

**Issue by AlexanderES** [BeckMillet/INFO442Team5#54]
**Describe the bug**
Not sure if this is a major bug but, if you add transactions that add up to more than your daily budget and then remove all the transactions from latest activity, your overall balance can exceed the daily budget

**To Reproduce**
1. Go to budget and set it to 200
2. Go to Enter Transaction
3. Add an item name and set the amount to 200 and then submit
3. Add another item name and set its price to 140 and then submit
4. Scroll down to Latest activity and select and remove the first item (200)
5. Select and remove the remaining item (140) in the latest activity
6. Scroll back up to the very top of the application
7. Look at overall balance and it will be at $340.00, higher than the daily budget of 200

**Expected behavior**
I was thinking that the overall balance would not exceed the daily budget, even if I removed a lot of items, since the user may have made some mistakes when adding new transactions, making them want to remove them after, and they wouldn't be able to have a balance greater than their budget

**Screenshots**
![overallBalance](https://user-images.githubusercontent.com/35088822/83847539-484b1300-a6c1-11ea-8346-a40b9534fbc2.png)

**Smartphone (please complete the following information):**
 - Device: iPhoneX (This application is designed exclusively for this screen size, please set your viewing size to match) on Chrome developer tool

**Additional context**
Should the daily budget be the maximum overall balance since this is assuming the user can't go over that amount (in this case the 200)?

**Comment by thoalala** [comment]
@AlexanderES Wow that's concerning. Thanks for the report - Some random issues occurred after deployment so we will definitely look into it and try to find the root cause.

**Not reproducible.** 

Test 1:
I created a new test account. 
- I Go to budget and set it to 200
- Go to Enter Transaction
- Add an item name and set the amount to 200 and then submit
- Add another item name and set its price to 140 and then submit
- Scroll down to Latest activity and select and remove the first item (200)
- Select and remove the remaining item (140) in the latest activity
- Scroll back up to the very top of the application
- Look at the overall balance, it is $200 which is correct. 

![image](https://user-images.githubusercontent.com/24668595/83850280-8ea27100-a6c5-11ea-86f8-0a7b4fcd251a.png)

Test 2:
Using an existing test account and followed all the steps.
- The overall balance is still 200 which is correct. 

**Team:** Please test on your own machines and comment if you can reproduce. Otherwise like this comment and we can label as not reproducible/non-issue on Monday.

**Comment by AlexanderES** [comment]
Sorry about that, when I noticed it I had already gone over 200, I had already added and removed a lot of transactions for different dates so I'm not too sure what caused it, I just assumed the steps I listed would still cause it. I just tried it with a new account and it seemed to work fine that time

**Comment by thoalala** [comment]
No worries! Please let us know if you ever find the reason for the overall balance becoming larger than the daily budget with transactions made on the same date. The problem may have occurred simply due to transactions added from future dates. We have acknowledged that usability issue and will fix it in the next release. :)

**Comment by AlexanderES** [comment]
Sounds good! I don't know if using it at midnight and reloading to change the main date had something to do with it either but I'll see if I run into the issue again
