### ISSUE TITLE
MAJOR: ** Sign in takes low character value for name field**

### ISSUE THREAD

**Issue by ashleyvarma** [BeckMillet/INFO442Team5#55]
Reproduction Steps:
1. Enter Sprout page
2. Prompt for sign in 
3. Enter email
4. Enter a single character in the 'first and last name' field

Description & Rationale: 
The sign-in feature allows users to input a single character as their first and last name. This is problematic because this naming convention is not possible irl, therefore it should not be possible on the site as well. 

**Screenshots**
![image](https://user-images.githubusercontent.com/26805404/83848741-2a7ead80-a6c3-11ea-9bee-b203bdce6055.png)

**Comment by thoalala** [comment]
**Team:** I don't think this is a bug? The create account form is managed by Firebox which we cannot edit. Let's label this as a non-issue on Monday and close as we allow low characters in names. If you believe this is a major issue for usability reasons let me know on Slack and I'll add it to the meeting agenda. 

**Edit** Although form validation could be better I guess. The issue is that Firebase is allowing this via the API. @bmaxwell99 what do you think? 

- Credentials are sent to the API, If only the email and password are sent to the API then it's on us to validate the name field. 
- If firebase requires the name field then it's out of our hands.

**Comment by shannongatta1** [comment]
This is a non-failure. We are not within the scope to fix Firebase.
